version: "3.9"

##
# IMPORTANT: Docker compose creates a shared network for its containers.
# As a result, ports from the right side are only accessible between containers.
# At the same time, ports from left side are only accessible by host.
# For example:
#
#   redis:
#     ports:
#       - 6380:6379
#
# To access Redis from container - use `redis://redis:6379`.
# To access Redis from host - use `redis://localost:6380`.
#
services:
  sidekiq_redis_7.2:
    image: redis:7.2
    container_name: sidekiq_redis_7.2
    restart: always
    volumes:
      - ./tmp/sidekiq_redis_7.2/data:/root/redis

  mysql_5.7:
    image: mysql:5.7
    container_name: mysql_5.7
    restart: always
    environment:
      MYSQL_DATABASE: mysql_5.7
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ./tmp/mysql_5.7:/var/lib/mysql

  ruby_2.7:
    build:
      context: .
      dockerfile: ./docker/ruby_2.7/Dockerfile
    container_name: ruby_2.7
    depends_on:
      - mysql_5.7
      - sidekiq_redis_7.2
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      SIDEKIQ_REDIS_HOST: ${SIDEKIQ_REDIS_HOST}
      SIDEKIQ_REDIS_PORT: ${SIDEKIQ_REDIS_PORT}
      SIDEKIQ_REDIS_URL: ${SIDEKIQ_REDIS_URL}
    stdin_open: true
    tty: true
    volumes:
      - .:/project

  ruby_3.0:
    build:
      context: .
      dockerfile: ./docker/ruby_3.0/Dockerfile
    container_name: ruby_3.0
    depends_on:
      - mysql_5.7
      - sidekiq_redis_7.2
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      SIDEKIQ_REDIS_HOST: ${SIDEKIQ_REDIS_HOST}
      SIDEKIQ_REDIS_PORT: ${SIDEKIQ_REDIS_PORT}
      SIDEKIQ_REDIS_URL: ${SIDEKIQ_REDIS_URL}
    stdin_open: true
    tty: true
    volumes:
      - .:/project

  ruby_3.1:
    build:
      context: .
      dockerfile: ./docker/ruby_3.1/Dockerfile
    container_name: ruby_3.1
    depends_on:
      - mysql_5.7
      - sidekiq_redis_7.2
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      SIDEKIQ_REDIS_HOST: ${SIDEKIQ_REDIS_HOST}
      SIDEKIQ_REDIS_PORT: ${SIDEKIQ_REDIS_PORT}
      SIDEKIQ_REDIS_URL: ${SIDEKIQ_REDIS_URL}
    stdin_open: true
    tty: true
    volumes:
      - .:/project

  ruby_3.2:
    build:
      context: .
      dockerfile: ./docker/ruby_3.2/Dockerfile
    container_name: ruby_3.2
    depends_on:
      - mysql_5.7
      - sidekiq_redis_7.2
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      SIDEKIQ_REDIS_HOST: ${SIDEKIQ_REDIS_PORT}}
      SIDEKIQ_REDIS_PORT: ${SIDEKIQ_REDIS_PORT}
      SIDEKIQ_REDIS_URL: ${SIDEKIQ_REDIS_URL}
    stdin_open: true
    tty: true
    volumes:
      - .:/project
